config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  devise_for :users

  devise_scope :user do
    get 'users/permit' => 'users/permit#permit'
    patch 'user/:id' => 'users/permit#permit_edit'
    post 'users/approve' => 'users/approval#approve_writer'
  end

  resources :user

  resources :categories

  resources :pictures

  get 'articles/tags/:tag' => 'articles#index', as: :tag

  resources :articles do
    get 'stats' => 'articles#stats', as: :stats
  end

  resources :features, :only => [:index, :show] do
    put :use
  end

  resources :questions do
    put :upvote
    put :downvote
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    # @questions = Question.where('report = ? OR report IS ?', false, nil)
    @questions = Question.where(report:[false, nil])
    @bug_reports = Question.where(report: true)
  end

  def show
    respond_with(@question)
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def upvote
    @question = Question.find(params[:question_id])
    @question.upvotes = @question.upvotes + 1
    if @question.save
      respond_to do |format|
        flash[:notice] = "Upvoted!"
        format.html { redirect_to questions_url }
      end
    end
  end

  def downvote
    @question = Question.find(params[:question_id])
    @question.upvotes = @question.upvotes - 1
    if @question.save
      respond_to do |format|
        flash[:notice] = "Downvoted!"
        format.html { redirect_to questions_url }
      end
    end
  end

  def create
    @question = Question.new(question_params)
    @question.upvotes = 0
    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_url, notice: 'Feedback successfully Noted' }
        format.json { render json: "{ \"status\" : \"success\" }"}
      else
        format.html { render :new }
        format.json { render json: "{ \"status\" : \"failed\" }"}
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to questions_url, notice: 'Your Question was updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'That issue was Solved.' }
    end
  end

  private
  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :description, :upvotes, :report)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

          <ul>
            <% @question.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br><br>

    <div class="row">
      <div class="form-group col-sm-6 col-sm-offset-3" align="center">
        <%= f.label :title, "Question" %><br>
        <%= f.text_field :title, required: true, class:"form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-sm-4 col-sm-offset-3" align="center">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: "form-control", style: "height: 200px" %>
      </div>
    </div>

    <!--<div class="row">-->
      <!--<div class="field">-->
        <!--<%= f.label :upvotes %><br>-->
        <!--<%= f.number_field :upvotes %>-->
      <!--</div>-->
    <!--</div>-->

    <div class="row">
      <div class="actions" align="center">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>

<% end %>

app/views/questions/edit.html.erb
<h1 align="center">Editing Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path, class: "btn btn-lg btn-block" %>

app/views/questions/index.html.erb
<div class="container-fluid" style="margin-top: 10px"><div class="row-fluid"><div class="text-center"><%= link_to 'Add Feedback Question', new_question_path ,class: 'new-btn btn btn-lg col-md-6 col-md-offset-3' %></div></div></div><br>
<h1 align="center">Listing Feedback questions</h1>

<table class="tabdaf table table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Upvotes</th>
    <th colspan="5">Links</th>
  </tr>
  </thead>

  <tbody>
  <% @questions.each do |question| %>
      <tr>
        <th><%= question.title.truncate(40) %></th>
        <td><%= question.upvotes.nil? ? 0 : question.upvotes %></td>
        <td class="trbtn"><%= link_to 'Upvote', question_upvote_path(question), method: :put, class: "btn btn-primary"%></td>
        <td class="trbtn"><%= link_to 'Downvote', question_downvote_path(question) , method: :put, class: "btn btn-primary" %></td>
        <td><%= link_to 'View this Issue', question_path(question) %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <% if can? :destroy, question %>
            <td><%= link_to 'Solved', question, method: :delete, data: { confirm: 'Are you sure this issue is resolved?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<h1 align="center">Listing Bug Reports</h1>
<table class="tabdaf table table-hover">
  <thead>
  <tr>
    <th>Package Name</th>
    <th>Upvotes</th>
    <th colspan="5">Links</th>
  </tr>
  </thead>

  <tbody>
  <% @bug_reports.each do |question| %>
      <tr>
        <th><%= question.title.truncate(35) %></th>
        <td><%= question.upvotes.nil? ? 0 : question.upvotes %></td>
        <td><%= link_to 'Upvote', question_upvote_path(question), method: :put, class: "btn btn-primary"%></td>
        <td><%= link_to 'Downvote', question_downvote_path(question) , method: :put, class: "btn btn-primary" %></td>
        <td><%= link_to 'View this Issue', question_path(question) %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <% if can? :destroy, question %>
            <td><%= link_to 'Solved', question, method: :delete, data: { confirm: 'Are you sure this issue is resolved?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<h1 align="center">New Feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path, class: "btn btn-lg btn-block"%>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<h2 align="center"><%= @question.title %></h2>

<div class="container" align="center">
  <div class="col-md-8 col-md-offset-2">
    <div class="jumbotron">
      <h4 style="padding: 10px; text-align: left"><%= @question.description %></h4>
    </div>
  </div>
</div>

<%= link_to 'Back', questions_path, class: 'btn btn-lg btn-block' %>