config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  devise_for :users

  devise_scope :user do
    get 'users/permit' => 'users/permit#permit'
    patch 'user/:id' => 'users/permit#permit_edit'
    post 'users/approve' => 'users/approval#approve_writer'
  end

  resources :user

  resources :categories

  resources :pictures

  get 'articles/tags/:tag' => 'articles#index', as: :tag

  resources :articles do
    get 'stats' => 'articles#stats', as: :stats
  end

  resources :features, :only => [:index, :show] do
    put :use
  end

  resources :questions do
    put :upvote
    put :downvote
  end

end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :category
  has_many :pictures, :dependent => :destroy
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :reads, :as => :readable

  # validate :valid_start_date

  # def valid_date(date)
  #   if date.present?
  #     errors[date] << "is not valid" unless valid_date?(date)
  #   end
  # end

  # def valid_date?(this_date)
  #     begin
  #       Date.parse(this_date)
  #     rescue
  #     else
  #     end
  # end

  # accepts_nested_attributes_for :pictures, :reject_if => lambda { |t| t['picture'].nil? }

  # scope :status, -> (status) { where status: status }
  # scope :location, -> (location_id) { where location_id: location_id }
  # scope :created, -> () { where("created_at >= ?", Time.zone.now.beginning_of_day) }

  def read_count
    reads.size
  end

  def today_count(a='all')
    if a == 'today'
      reads.where("created_at >= ?", Time.zone.now.beginning_of_day).size
    elsif a == 'all'
      reads.size
    end
  end

  def range_count(start_params, end_params)
    # start_date = DateTime.new(start_params['date(1i)'].to_i, start_params['date(2i)'].to_i, start_params['date(3i)'].to_i)
    # end_date = DateTime.new(end_params['date(1i)'].to_i, end_params['date(2i)'].to_i, end_params['date(3i)'].to_i)
    start_date = DateTime.strptime(start_params, '%m/%d/%Y')
    end_date = DateTime.strptime(end_params, '%m/%d/%Y')
    reads.where("created_at < ? AND created_at > ?", end_date, start_date).size
  rescue ArgumentError
    reads.size
  end

  def unique_read_count
    reads.group(:ip_address).length
  end

  def unique_range_count(start_params, end_params)
    # start_date = DateTime.new(start_params['date(1i)'].to_i, start_params['date(2i)'].to_i, start_params['date(3i)'].to_i)
    # end_date = DateTime.new(end_params['date(1i)'].to_i, end_params['date(2i)'].to_i, end_params['date(3i)'].to_i)
    start_date = DateTime.strptime(start_params, '%m/%d/%Y')
    end_date = DateTime.strptime(end_params, '%m/%d/%Y')
    reads.where("created_at < ? AND created_at > ?", end_date, start_date).group(:ip_address).length
  rescue ArgumentError
    reads.group(:ip_address).length
  end

  def self.tagged_with(name)
    Tag.find_by_name!(name).articles
  end

  def self.tag_counts
    Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end

  def tag_name
    tag.name if tag
  end

  def tag_name=(name)
    self.tag = Tag.find_or_create_by_name(name) unless name.blank?
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # before_action :admin_only, :except => :show
  authorize_resource
  before_filter :log_read, :only=> [:show]


  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end

  def stats
    if params[:article_id]
      @article = Article.find(params[:article_id])
    end
  end

  def log_read
    @article = Article.find(params[:id])
    if !request.headers['many'].nil?
      request.headers[:many].to_i.times do
        @article.reads.create(ip_address: request.remote_ip, user_id:current_user.nil? ? 0 : current_user.id)
      end
    else
      @article.reads.create(ip_address: request.remote_ip, user_id:current_user.nil? ? 0 : current_user.id)
    end
  end

  def show
    render :layout => false
  end

  def new
    # authorize! :create, @article
    @article = Article.new
  end

  def edit
    # authorize! :update, @article
  end

  def create
    # authorize! :create, @article

    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        if params[:image]
          @article.pictures.create(image: params[:image])
        end
        format.html { redirect_to articles_url, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    # authorize! :update, @article

    respond_to do |format|
      if @article.update(article_params)
        if params[:image]
          @article.pictures.create(image: params[:image])
        end
        format.html { redirect_to articles_url, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # authorize! :destroy, @article
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :category_id, :tag_list, :many)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, html: { multipart: true } do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% @article.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <br><br>
    
    <div class="row">

      <div class="form-group col-lg-6 col-lg-offset-2" align="center">
        <%= f.label :title %><br>
        <%= f.text_field :title, required: true, class: "form-control" %>
      </div>

      <div class="form-group col-lg-2" align="center">
        <%= f.label :category %><br>
        <%= f.select(:category_id, Category.all.collect {|u| [u.name, u.id]}, :prompt => 'Select', class: "form-control") %>
      </div>

    </div>

    <div class="row">
      <div class="form-group col-lg-8 col-lg-offset-2" align="center">
        <%= f.label :text, "Article Content" %><br>
        <%= f.text_area :text, required: true, class: "form-control", style: "height: 300px" %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-lg-8 col-lg-offset-2" align="center">
        <%= f.label :tag_list, "Tags (saperated by commas)" %><br>
        <%= f.text_field :tag_list, class: "form-control" %>
      </div>
    </div>

    <div class="row">
      <div class="form-group" align="center">
        <%= file_field_tag :image, class: "form-control-file" %>
      </div>
    </div>

    <div class="row">
      <div class="form-group" align="center">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>

    <div id="notifydiv">
      <p>
        Only a limited number of tags are allowed while editing the articles:<br/> like &lt;p&gt;, &lt;img&gt;, &lt;a href&gt;, &lt;div&gt; and some simple formatting tags.
      </p>
    </div>

<% end %>

app/views/articles/edit.html.erb
<h1 align="center">Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: "btn btn-lg btn-block" %>

app/views/articles/index.html.erb
<h1 align="center">Listing articles</h1>

<% if can? :create, Article  %>
    <div class="container-fluid"><div class="row-fluid"><div class="text-center"><%= link_to 'New Article', new_article_path ,class: 'new-btn btn btn-lg col-md-6 col-md-offset-3' %></div></div></div><br>
<% else %>
    <% if !current_user.nil? %>
        <% if user_signed_in? %>
            <div class="alert alert-danger">
              <strong>Alert!</strong> You are still not approved, Please wait for admin to approve.
            </div>
        <% end %>
    <% else %>
        <div class="alert alert-danger">
          <strong>Alert!</strong> Please Sign In First.
        </div>
    <% end %>
<% end %>


<table class="tabdaf table table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Category</th>
    <th>Pictures</th>
    <th colspan="4">Links</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
      <tr>
        <th scope="row"><%= article.title %></th>
        <td><%= truncate(article.text, omission: "... (continued)", :length => 100) %>
          <p>
            Tags: <%= raw article.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %>
          </p>
        </td>
        <td><%= article.category.nil? ? 'Other' : article.category.name %></td>
        <td>
          <% article.pictures.each do |picture| %>
              <%= link_to image_tag(picture.image.url(:low), class: 'img-responsive'), picture.image.url %>
          <% end %>
        </td>
        <td><%= link_to 'Show', article %></td>
        <% if can? :update, article%>
            <td><%= link_to 'Stats', article_stats_path(article) %></td>
        <% end %>
        <% if can? :update, article  %>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <% end %>
        <% if can? :destroy, article  %>
            <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1 align="center">New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: "btn btn-lg btn-block" %>

app/views/articles/show.html.erb
<div class="page-header">
  <h1 align="center">
    <strong><%= @article.title %></strong>
  </h1>
</div>

<p class="lead" style="font-size: large">
  <%= sanitize(@article.text, tags: %w(a img h1 h2 h3 b i u p div), attributes: %w(id src href class)) %>
</p>

<p>
  <strong>Related Pictures:</strong><br>
  <% @article.pictures.each do |picture| %>
      <%= link_to image_tag(picture.image.url(:low)), picture.image.url %>
  <% end %>
</p>

app/views/articles/show_old.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Pictures:</strong>
  <% @article.pictures.each do |picture| %>
      <%= link_to image_tag(picture.image.url(:low)), picture.image.url %>
  <% end %>
</p>

<%= link_to 'Edit', edit_article_path(@article), class: "btn" %>
<%= link_to 'Back', articles_path, class: "btn" %>

app/views/articles/stats.html.erb
<div class="jmb container-fluid col-md-6 col-md-offset-3">

  <div class="jumbotron">
    <% if !params[:from].nil? && !params[:to].nil? %>
        <h1><%= @article.range_count(params[:from], params[:to]) %></h1>
    <% else %>
        <h1><%= @article.read_count %></h1>
    <% end %>
    <p>Read Count</p>
  </div>
</div>

<div class="jmb container-fluid col-md-6 col-md-offset-3">
  <div class="jumbotron">
    <% if !params[:from].nil? && !params[:to].nil? %>
        <h1><%= @article.unique_range_count(params[:from], params[:to]) %></h1>
    <% else %>
        <h1><%= @article.unique_read_count %></h1>
    <% end %>
    <p>Unique Read Count</p>
  </div>
</div>

<div id="filterdiv">
  <%= form_tag article_stats_path, method: :get do %>
      <h4 align="center">Filter Reads:</h4>
      <p>
        <%= label_tag 'From Date:' %>
        <br>
        <%= text_field_tag :from, nil, class: 'datepicker' %>
        <br>
        <%= label_tag 'To Date:' %>
        <br>
        <%= text_field_tag :to, nil, class: 'datepicker' %>
        <br>
      </p>
      <div align="center">
        <%= submit_tag 'Search', :name => nil, class: 'btn'%>
      </div>
  <% end %>
</div>