config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  devise_for :users

  devise_scope :user do
    get 'users/permit' => 'users/permit#permit'
    patch 'user/:id' => 'users/permit#permit_edit'
    post 'users/approve' => 'users/approval#approve_writer'
  end

  resources :user

  resources :categories

  resources :pictures

  get 'articles/tags/:tag' => 'articles#index', as: :tag

  resources :articles do
    get 'stats' => 'articles#stats', as: :stats
  end

  resources :features, :only => [:index, :show] do
    put :use
  end

  resources :questions do
    put :upvote
    put :downvote
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seraphimdroid Knowledge Base</title>
  <!--<link rel="icon" href="assets/favicon.png">-->
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-static-top navbar-dark navbar-inverse" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"> Knowledge Base</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Articles', articles_path %></li>
            <li><%= link_to 'Categories', categories_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Uploaded Pictures', pictures_path %></li>
          </ul>
        </li>
        <% if can? :create, User  %>
            <li><%= link_to 'Admin Users', users_permit_path %></li>
        <% end %>
        <% if !current_user.nil? && current_user.admin? %>
            <li><%= link_to 'Feature Usage Stats', features_path %></li>
        <% end %>
        <% if can? :destroy, Question %>
            <li><%= link_to 'Approve Feedback Questions', questions_path %></li>
        <% else %>
            <li><%= link_to 'Provide Feedback', questions_path %></li>
        <% end %>
        <% if !current_user.nil? && !current_user.writer? && !current_user.admin? %>
            <li><%= link_to 'Become a Writer', {controller: 'users/approval', action: 'approve_writer', wflag: 'true', id: current_user.id }, method: :post %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
              <!--Welcome, <%= current_user.email %> -->
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
          <% else %>
              <%= link_to "Sign in", new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% if flash[:alert] %>
    <div class="alert alert-danger">
      <strong>Alert!</strong> <%= flash[:alert] %>
    </div>
<% end %>
<%= yield %>
<br><br>
<% if flash[:notice] %>
    <div class="alert alert-info" id="bottom-info">
      <strong>Info:</strong> <%= flash[:notice] %>
    </div>
<% end %>
</body>
</html>